language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ artful universe multiverse"
 - sudo apt-get update -qq
 - sudo apt-get install -y libsodium18 python-setuptools
 - python setup.py develop --always-unzip

script:
 - python -m unittest discover --start-directory tests

notifications:
  email: false
